sudo: required

services:
- docker

language: go

go:
- "1.10"

go_import_path: github.com/container-mgmt/dedicated-portal

install:
- wget https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
- echo 31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315 dep-linux-amd64 | sha256sum -c
- mv dep-linux-amd64 ~/bin/dep
- chmod +x ~/bin/dep
- go get github.com/jteeuwen/go-bindata/go-bindata
- go get golang.org/x/lint/golint
- go get github.com/client9/misspell/cmd/misspell
- go get golang.org/x/tools/cmd/goimports

script:
- make images
- make lint
- misspell -error cmd/** pkg/** README.adoc
