#
# Reduce the size of the `vendor` directory excluding unused packages, tests and
# other files that aren't needed.
#
[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang-migrate/migrate"
  version = "3.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/auth0/go-jwt-middleware"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "v0.3.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "v3.2.0"

[[constraint]]
  name = "github.com/openshift/cluster-operator"
  branch = "master"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.0"
[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "kubernetes-1.9.0"
